name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -t europe-west2-docker.pkg.dev/propane-avatar-327810/sageroom/sageroom-nginx .

      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: europe-west2-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CI }}

      - name: Push new image
        run: docker push europe-west2-docker.pkg.dev/propane-avatar-327810/sageroom/sageroom-nginx